name: Build Firmware

"on":
  push:
    branches: [main]
    paths:
      - 'firmware/**'
      - '.forgejo/workflows/build.yaml'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apk install --no-cache make cmake gcc-arm-none-eabi

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Configure
        run: |
          mkdir -p firmware/build
          cd firmware/build
          cmake ..

      - name: Build
        run: |
          cd firmware/build
          make
